# Generated by Django 6.0.4 on 2026-05-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_message_reply_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreed_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "poster_deposit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "developer_deposit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("poster_paid", models.BooleanField(default=False)),
                ("developer_paid", models.BooleanField(default=False)),
                (
                    "poster_tx_ref",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "developer_tx_ref",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("agreed", "Agreed & Unfunded"),
                            ("partially_funded", "Partially Funded"),
                            ("fully_funded", "Fully Funded / Active"),
                            ("completed", "Completed & Released"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_agreements",
                        to="problems.problem",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
