# Generated by Django 6.0.4 on 2026-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ghana_card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_picture",
            field=models.ImageField(blank=True, null=True, upload_to="id_pictures/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("poster", "Problem Poster"),
                    ("developer", "Developer"),
                    ("admin", "Administrator"),
                ],
                default="poster",
                max_length=20,
            ),
        ),
    ]
