# Generated by Django 6.0.4 on 2026-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_ghana_card_number_customuser_id_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="id_picture",
        ),
        migrations.AddField(
            model_name="customuser",
            name="ghana_card_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="id_pictures/back/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ghana_card_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="id_pictures/front/"
            ),
        ),
    ]
