# Generated by Django 6.0.4 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_browser_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="github_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
